//------------------------------------------------------------------------------
// <auto-generated>
//     Resources for Flappy Re-Dovah Launcher (trimmed to used assets only).
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlappyReDovahLauncher.Properties {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager(
                        "FlappyReDovahLauncher.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap bg_LBackground {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("bg_LBackground", resourceCulture); }
        }

        internal static System.Drawing.Bitmap icon_discord {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("icon_discord", resourceCulture); }
        }

        internal static System.Drawing.Bitmap icon_boosty {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("icon_boosty", resourceCulture); }
        }

        internal static System.Drawing.Bitmap edge_bar_fill {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("edge_bar_fill", resourceCulture); }
        }

        internal static System.Drawing.Bitmap edge_bar_frame {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("edge_bar_frame", resourceCulture); }
        }

        internal static System.Drawing.Bitmap edge_bar_track {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("edge_bar_track", resourceCulture); }
        }

        internal static System.Drawing.Bitmap cross {
            get { return (System.Drawing.Bitmap)ResourceManager.GetObject("cross", resourceCulture); }
        }
    }
}
