<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Flappy Launcher</AssemblyName>
    <RootNamespace>FlappyReDovahLauncher</RootNamespace>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <StartupObject>FlappyReDovahLauncher.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\7za.exe" />
    <EmbeddedResource Include="Resources\7za.dll" />
    <EmbeddedResource Include="Resources\7zxa.dll" />
  </ItemGroup>
</Project>